-- Run this in Supabase SQL Editor

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  username text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

alter table public.profiles
  alter column username set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_username_length_chk'
  ) then
    alter table public.profiles
      add constraint profiles_username_length_chk
      check (char_length(trim(username)) between 3 and 40);
  end if;
end $$;

create or replace function public.set_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_profiles_updated_at();

-- Optional helper: create profile automatically on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, username)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

-- Account deletion for logged users
create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  delete from auth.users where id = auth.uid();
end;
$$;

revoke all on function public.delete_my_account() from public;
grant execute on function public.delete_my_account() to authenticated;

-- Game results
create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  song_title text,
  artist text,
  mode text not null default 'normal' check (mode in ('normal', 'cloze', 'rhythm')),
  wpm integer not null default 0,
  accuracy integer not null default 0,
  words_correct integer not null default 0,
  words_wrong integer not null default 0,
  total_chars integer not null default 0,
  incorrect_chars integer not null default 0,
  extra_chars integer not null default 0,
  duration_seconds integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_game_results_user_created_at
on public.game_results(user_id, created_at desc);

alter table public.game_results enable row level security;

drop policy if exists "game_results_select_own" on public.game_results;
create policy "game_results_select_own"
on public.game_results
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "game_results_insert_own" on public.game_results;
create policy "game_results_insert_own"
on public.game_results
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "game_results_delete_own" on public.game_results;
create policy "game_results_delete_own"
on public.game_results
for delete
to authenticated
using (auth.uid() = user_id);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'game_results_accuracy_chk'
  ) then
    alter table public.game_results
      add constraint game_results_accuracy_chk
      check (accuracy between 0 and 100);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'game_results_non_negative_chk'
  ) then
    alter table public.game_results
      add constraint game_results_non_negative_chk
      check (
        wpm >= 0 and
        words_correct >= 0 and
        words_wrong >= 0 and
        total_chars >= 0 and
        incorrect_chars >= 0 and
        extra_chars >= 0 and
        duration_seconds >= 0
      );
  end if;
end $$;
